### ISSUE TITLE
Kontroller at vi kan bruke maskinporten til autentisering av private.

### ISSUE THREAD

**Issue by AndersOstmoe** [ks-no/gi-arkiv-2.0#10]

**Comment by ekorra** [comment]
Maksinporten kan brukes av private virksomheter som tilbyr eller konsumerer tjenester fra det offentlige

Må underskrive egne bruksvilkår: https://samarbeid.difi.no/bruksvilkar/bruksvilkar-private-kunder-i-maskinporten
