### ISSUE TITLE
Behandlingsansvarlig på registrering

### ISSUE THREAD

**Issue by sturtzel** [ks-no/gi-arkiv-2.0#100]
I modellen i dag er alle interne likeverdige. Dette er i tråd med Noark 5 avleveringsmodell, men ikke med vanlige behandlingsregler, Noark 4 og GeoIntegrasjon. I Noark 4 het feltet AM.BEHANSV (0/1 for false/true) og anga hvilke av de interne som var ansvarlig for journalposten.

For saksarkivene må det enten inn et slikt felt eller så må det inn behandlingsregler, f.eks. at første interne er den behandlingsansvarlige.

Ref. ellers https://github.com/ks-no/fiks-arkiv/issues/26 for standardverdier for kodelister om dette skulle vært håndtert som kodeverdi for korrespondanseparttype.

**Comment by jarleborsheim** [comment]
Tolker jeg det riktig ved at vi kan løse dette ved å kun legge til `Behandlingsansvarlig` i kodelisten for korrespondanseparttype? 
Slik som dette?

```
  public static class KorrespondanseparttypeKoder
    {
        public static readonly Kode Avsender = new Kode("EA", "Avsender");
        public static readonly Kode Mottaker = new Kode("EM", "Mottaker");
        public static readonly Kode Kopimottaker = new Kode("EK", "Kopimottaker");
        public static readonly Kode Gruppemottaker = new Kode("GM", "Gruppemottaker");
        public static readonly Kode InternAvsender = new Kode("IA", "Intern avsender");
        public static readonly Kode InternMottaker = new Kode("IM", "Intern mottaker");
        public static readonly Kode InternKopimottaker = new Kode("IK", "Intern kopimottaker");
        public static readonly Kode Behandlingsansvarlig = new Kode("BH", "Behandlingsansvarlig");
    }
```

**Comment by sturtzel** [comment]
Med litt logikk, ja. Behandlingsansvarlig vil noen ganger være intern avsender og andre ganger intern mottager.

I GI er det et eget attributt i tillegg til korrespondanserparttype:
<xs:element name="korrespondanseparttype" type="tns:Korrespondanseparttype" minOccurs="1" maxOccurs="1"/>
<xs:element name="behandlingsansvarlig" type="xs:string" minOccurs="0" maxOccurs="1"/>

Verdiene der er 0: False eller 1: True

Jeg er åpen for begge løsninger, ser at neste møte ikke er før neste torsdag. Men vi burde få landet denne før møtet.

**Comment by jarleborsheim** [comment]
Det er kanskje tydeligere med det nye attributtet `behandlingsansvarlig`? 
Se forslag her: https://github.com/ks-no/fiks-arkiv-specification/pull/35
Jeg har da gjort endringen i arkivmelding (inn) og i arkivstruktur (ut).
Men er det enda mer tydelig med `erBehandlingsansvarlig` siden det er en bool?

**Comment by sturtzel** [comment]
Ja, legg gjerne på "er". Da er ingen i tvil.

**Comment by jarleborsheim** [comment]
Da har jeg endelig forslag her: https://github.com/ks-no/fiks-arkiv-specification/pull/35

**Comment by jarleborsheim** [comment]
Er denne ok og jeg kan merge pull request inn, eller skal vi vente til etter møtet neste torsdag? @sturtzel

**Comment by sturtzel** [comment]
Jeg foreslår at du tar dette inn nå. Løsningen er kompatibel med GI og dermed kurant både for klient og tjener.

**Comment by jarleborsheim** [comment]
Da er den merget inn og jeg stenger denne saken
