### ISSUE TITLE
Mappe i arkivstruktur har avsluttetDato og avsluttetAv som required

### ISSUE THREAD

**Issue by jarleborsheim** [ks-no/gi-arkiv-2.0#102]
Dette kom inn som et spørsmål fra Slack:

> Hello, testing the  hent requests I noticed that the mappe.hent.resultat payload requires the provided back mappe/saksmappe has the fields avsluttetDato and avsluttetAv populated, which means the case file is closed, based on the schemas definition :
from `https://github.com/ks-no/fiks-arkiv-specification/blob/7e99b39efc0d182185fad6ce0e2aea099b8049f2/Schema/V1/arkivstruktur.xsd`
<xs:element name="avsluttetDato" type="n5mdk:avsluttetDato"/>
<xs:element name="avsluttetAv" type="n5mdk:avsluttetAv"/>
When creating a Saksmappe, it does not need to be closed (the two fields are not mandatory), so the two fields are not set for newly created case files (unless status of the case file is explcitly set to closed). Is it on purpose that only case file which are closed can be retrieved back using the mappe.hent query ?

**Comment by jarleborsheim** [comment]
Avslutter denne da PR ble godkjent

**Comment by sturtzel** [comment]
Fint! Disse feltene skal ha verdi i avleveringen. Dette gjelder alle objekter der disse feltene måtte finnes (bare svarte opp fra PC-en til Nisha i går siden jeg hadde pakket sammen etter møte). Har ikke sjekket registreringer og andre objekter.
