### ISSUE TITLE
Endre id'er til å følge pattern

### ISSUE THREAD

**Issue by jarleborsheim** [ks-no/gi-arkiv-2.0#103]
SystemID skal være på Registrering, Mappe, Dokument og DokumentObjekt.

Andre, som part, kryssreferanse og merknad skal ha en id med navn som er av typen partID, kryssreferanseID og merknadID. De trenger altså ikke systemID. 
Id'ene kan ligge i metadatakatalog.

**Comment by jarleborsheim** [comment]
Mens jeg jobber med denne ser jeg at i no.ks.fiks.arkiv.v1.arkivering.arkivmelding.xsd finnes det en complexType av typen `abstraktNasjonalidentifikatorType` som ikke ser ut til å være brukt noe sted. Slette?

**Comment by sturtzel** [comment]
Den kom vel inn som overordnet type for matrikkel, bygning, ... Hvis du ikke finner den igjen kan du slette den. Jeg får ikke sjekket: Litt dårlig nettilgang nå på sørlandsbanen i skogen etter Kongsberg.

**Comment by jarleborsheim** [comment]
PR er godkjent og merget og vi stenger denne saken
