### ISSUE TITLE
Skal klassifikasjonssystem være et kodefelt?

### ISSUE THREAD

**Issue by jarleborsheim** [ks-no/gi-arkiv-2.0#104]
I arkivmelding og arkivstruktur. 
Ref kommentar i PR her: https://github.com/ks-no/fiks-arkiv-specification/pull/43#discussion_r951106272

**Comment by sturtzel** [comment]
Jeg foreslår at det lages ordinært kodeobjekt for klassifikasjonssystem og at dette brukes der det i dag angis klassifikasjonssystem.

Ved søk bør det være koden som angis.

Hvis et arkivsystem ikke benytter kode i sitt oppsett kan de sette kode lik beskrivelsen (gjelder for så vidt alle koder).

**Comment by jarleborsheim** [comment]
Erstatte klassifikasjonssystem under klassifikasjon med klassifikasjonsID. Slette klassifikasjonssystem fra metadatakatalog
Gjøre det gjennomgående i alle steder hvor det er som i arkivstruktur

**Comment by jarleborsheim** [comment]
Stenger denne da den er gjort
