### ISSUE TITLE
MappeOppdatering mangler skjerming og gradering

### ISSUE THREAD

**Issue by sturtzel** [ks-no/gi-arkiv-2.0#112]
Oppdaget at skjerming og gradering kun finnes på registrering og dokumentbeskrivelse.

Disse opplysningene må kunne oppdateres også for mappe.

https://github.com/ks-no/fiks-arkiv-specification/blob/main/Schema/V1/no.ks.fiks.arkiv.v1.arkivering.arkivmelding.oppdater.xsd

<xs:complexType name="mappeOppdatering">
            <xs:element name="skjerming" type="arkivmelding:skjerming" minOccurs="0"/>
            <xs:element name="gradering" type="arkivmelding:gradering" minOccurs="0"/>

**Comment by jarleborsheim** [comment]
Stenger denne da den er løst
