### ISSUE TITLE
Merknad.merknadRegistrertAv bør ha minOccurs 0

### ISSUE THREAD

**Issue by sturtzel** [ks-no/gi-arkiv-2.0#118]
Alle andre tilsvarende har minOccurs 0.
Også merknadsdato bør ha minOccurs 0.

I GeoIntegrasjon har de dette.

Siden arkivmeldingen også skal kunne brukes til eFormidling vil et krav om minOccurs 1 medføre at objektet i praksis ikke kan brukes. Det er allerede registrert som et problem i den bruken.

**Comment by jarleborsheim** [comment]
Løst og vi stenger denne oppgaven
