### ISSUE TITLE
Datamodell for personnavn

### ISSUE THREAD

**Issue by sturtzel** [ks-no/gi-arkiv-2.0#12]
I Noark 5 er det kun navn. I GI 1.1 er det flere felt.

Det mest fleksible er at det lages objekt tilsvarende kode-objektet med valgfrihet i utfylling. Da er det mulig å ha felt som
Navn
Initialer
Identifikator (f.eks. den fra AD)
...

Eksakt hvilke kan diskuteres, men av hensyn til GI 1.1 bør de to første være med.

**Comment by torkjetil** [comment]
<xs:complexType name="saksbehandlerType">
<xs:sequence>
<xs:element type="n5mdk:saksbehandler" name="saksbehandler" minOccurs="0"/>
<xs:element type="xs:string" name="initialer" minOccurs="0"/>
<xs:element type="xs:string" name="identifikator" minOccurs="0"/>
</xs:sequence>
</xs:complexType>

**Comment by jarleborsheim** [comment]
Vi tar denne også opp på neste møte

**Comment by jarleborsheim** [comment]
Det må legges til identifikator. 

id, initialer, epost og navn.
Id kan være hva som helst. Det er opp til systemet og hva som brukes som id. minoccurs=0 på alle

**Comment by jarleborsheim** [comment]
@sturtzel tar du en titt på PR? https://github.com/ks-no/fiks-arkiv-specification/pull/55

**Comment by jarleborsheim** [comment]
Stenger saken da begge PR er godkjent og merget
