### ISSUE TITLE
Datamodell for organisasjonsenhet

### ISSUE THREAD

**Issue by sturtzel** [ks-no/gi-arkiv-2.0#13]
Noark 5 er det kun navn. I GI 1.1 er det flere felt.

Det mest fleksible er at det lages objekt tilsvarende kode-objektet med valgfrihet i utfylling. Da er det mulig å ha felt som
Navn
Initialer / unik kode
Identifikator (f.eks. den fra AD)
...

Eksakt hvilke kan diskuteres, men av hensyn til GI 1.1 bør de to første være med.

**Comment by HarryMyrene** [comment]
Visma: Må i tilfelle være valgfritt å benytte

**Comment by sturtzel** [comment]
Skjønner ikke kommentaren fra Visma. Hvis det blir objekt er det selvsagt mulig å ikke ta det med, eller å bruke kun noen av feltene (som gjør at arkivet kompletterer).

**Comment by jarleborsheim** [comment]
Vi tar denne opp på neste møte

**Comment by jarleborsheim** [comment]
Endre saksansvarlig, administrativenhet og saksbehandler i metadatakatalog til å bli typen kode

**Comment by jarleborsheim** [comment]
Stenger saken da begge PR er godkjent og merget
