### ISSUE TITLE
Støtte for GI 1.1

### ISSUE THREAD

**Issue by sturtzel** [ks-no/gi-arkiv-2.0#14]
Det er i praksis ikke mulig å lage et 1.1-kompatibelt grensesnitt da GI 2.0 forlanger arkivering av ferdige journalposter med dokumenter mens GI 1.1 har en rekke kall for å få til dette.

Da mange organisasjoner er trege med å oppgradere arkivet er det mulig å fremskynde overgangen til GI 2.0 ved å gjøre det motsatte: GI 2.0-grensesnitt som pakkes ut til GI 1.1-kall. Koden for dette bør være åpen slik at leverandørene kan tilpasse for eksisterende løsninger og dermed få ut støtten raskt.

Det er også behov for en mulighet for å kortslutte FIKS IO der fagsystem og arkiv er innenfor samme domene. Dette er samme behov som ved testing av serverimplementasjonen.

**Comment by jarleborsheim** [comment]
Denne har blitt bestemt at ikke skal gjøres
