### ISSUE TITLE
Skal en mappe kunne ligge i flere arkivdeler? Mangler attributtet arkivdel?

### ISSUE THREAD

**Issue by sturtzel** [ks-no/gi-arkiv-2.0#15]
Mappe mangler attributtet arkivdel, men har 0:m på referanseArkivdel.

Den siste er ikke ordning, men reelle referanser av type "se også".

Noark 5 har ikke eget attributt i mappe for arkivdel siden det er en hierarkisk avleveringsmodell der mappene er ordnet inn i arkivdeler.

**Comment by HarryMyrene** [comment]
Visma: Ser ikke dette behovet, men kanskje noe fra brukstilfelelt til husbanken?

**Comment by sturtzel** [comment]
Dette er kommentar til hvordan xsd-en ser ut i dag. Den har 0:m, noe jeg tviler på om noen har bruk for.
