### ISSUE TITLE
Hvordan skille personnavn fra organisasjonsnavn

### ISSUE THREAD

**Issue by sturtzel** [ks-no/gi-arkiv-2.0#16]
eInnsyn forlanger tagging av personnavn grunnet begrensninger i søk etter ett år.

Det er ingenting i datamodellen p.t. som gjør det mulig å skille disse.

**Comment by torkjetil** [comment]
erPersonnavn - boolean er nyttig :)

**Comment by HarryMyrene** [comment]
Visma: Forslaget fra torkjetil vil jo berøre alle fagsystemene som skal arkivere. Synes ikke dette er noen god løsning, kanskje heller styre på nasjonale identifikatorer (fnr/orgnr) når disse kommer inn i standarden.

**Comment by sturtzel** [comment]
Ikke alle fagsystemer legger på nasjonale identifikatorer.

Fagsystemene vet normalt om det er person eller organisasjon som er (korrespondanse-)part. Har de et organisasjonsnummer er det organisasjon, fødselsnummer er det person. Standardverdien vil være false og ikke satt betyr at det blir som i dag i arkivet.

**Comment by torkjetil** [comment]
Relatert til https://github.com/arkivverket/noark5-standard/issues/29? og https://github.com/arkivverket/noark5-standard/issues/68?

**Comment by jarleborsheim** [comment]
Er denne fremdeles aktuell?

**Comment by sturtzel** [comment]
Vi har nå type ID, men ikke angivelse av personnavn. eInnsyn trenger å vite. Usikker på om ID-en er nok.

**Comment by jarleborsheim** [comment]
Forslag på 3 typer
**Person:**
fnr, fornavn, etternavn
**Virksomhet:**
orgnr, navn
**Kontaktperson:**
Virksomhet, orgnr, kontaktperson,

**Comment by jarleborsheim** [comment]
Denne må fikses. Vi tar det opp igjen 25.08.2022

**Comment by jarleborsheim** [comment]
Vi endrer personnavn til erpersonnavn i metadatakatalog. Vi lar den være en streng

**Comment by jarleborsheim** [comment]
Stenger denne da PR er  godkjent og merget
