### ISSUE TITLE
Versjonshåndtering

### ISSUE THREAD

**Issue by sturtzel** [ks-no/gi-arkiv-2.0#18]
Bør det være et kall i GI som angir hvilken versjon(er) av standarden server støtter?
Bør det være data i arkivmeldingen som angir versjon av denne?

Det er ikke gitt at klient og server er i sync og man kan ikke forlange at begge sider skal støtte alle tidligere versjoner.

**Comment by torkjetil** [comment]
Dette står i protokollen - i FIKS IO - katalog

**Comment by torkjetil** [comment]
no.ks.fiks.gi.arkivintegrasjon.oppdatering.basis.arkivmelding.v1
