### ISSUE TITLE
Servers unike ID på objektene, referanser til gjeldende Noark 5

### ISSUE THREAD

**Issue by sturtzel** [ks-no/gi-arkiv-2.0#19]
I utkastet til arkivmelding er det som for Noark 5.5 lagt inn krav om UID som unik ID. Dette var nytt i denne revisjonen av Noark 5 og er derfor neppe alment rullet ut.

For standardens del er det irrelevant hva slags format det er på identifikatoren så lenge den er entydig. Dette kravet bør derfor fjernes fra GI.

Referanser til gjeldende Noark 5 i metadefinisjonene i GI gjør standarden sårbar. Hvis Noark endrer vil endringen umiddelbart få konsekvenser for eksisterende integrasjoner som da fort kan feile. Ref. bl.a. UID som kom som presisering i Noark 5.5.

Referanser til Noark må enten være i form av kopi eller være med versjonsangivelse.

**Comment by sturtzel** [comment]
I utkastet til arkivmelding er det som for Noark 5.5 lagt inn krav om UID som unik ID. Dette var nytt i denne revisjonen av Noark 5 og er derfor neppe alment rullet ut.

For standardens del er det irrelevant hva slags format det er på identifikatoren så lenge den er entydig. Dette kravet bør derfor fjernes fra GI.

Referanser til gjeldende Noark 5 i metadefinisjonene i GI gjør standarden sårbar. Hvis Noark endrer vil endringen umiddelbart få konsekvenser for eksisterende integrasjoner som da fort kan feile. Ref. bl.a. UID som kom som presisering i Noark 5.5.

Referanser til Noark må enten være i form av kopi eller være med versjonsangivelse.

**Comment by JanIvarMoldekleiv** [comment]
Enig i kommentaren til @sturtzel  - vi kan endre denne til string.

**Comment by torkjetil** [comment]
Enig pga bakoverkompabilitet

**Comment by JanIvarMoldekleiv** [comment]
Sjekket inn endring - brukte n5mdk.systemid.

**Comment by torkjetil** [comment]
Løst ser det ut som
