### ISSUE TITLE
Forsendelse

### ISSUE THREAD

**Issue by sturtzel** [ks-no/gi-arkiv-2.0#20]
Ref. også brukstilfelle 8.

Er forsendelse en arkivfunksjon eller er det en saksfunksjon? Hvis ikke fagsystemet ønsker å håndtere alle kanaler selv, bør dette håndteres av en revisjon av GI Sak? Ref. også brukstilfelle 14 ang. behov for å oppdatere GI Sak.

For å kunne følge opp en forsendelse trengs det flere attributter på korrespondansepart enn forsendelsesmåte.
Dato?
Status?
Sporingsreferanse fra systemet som står for forsendelsen (SvarUt, eFormiding, ...)?

**Comment by HarryMyrene** [comment]
Visma: Sky-tjenesten styrer forsendelser selv.

**Comment by sturtzel** [comment]
Det er vel landet at dette er en sak-tjeneste som enten håndteres av fagsystemet selv eller via (ikke spesifisert tjeneste i) GI Sak.

Men det er like fullt nyttig å kunne se om 10 år at denne ble sendt elektronisk til bruker som åpnet den tre dager senere. Det har noe å si for datamodellen.

**Comment by sturtzel** [comment]
Status bør inn i logg.

**Comment by torkjetil** [comment]
Ønskelig inn som hendelseslogg som tilrettelagt i N5 tjenestegrensensitt - https://github.com/arkivverket/noark5-tjenestegrensesnitt-standard/blob/master/xsd/loggingogsporing.xsd

**Comment by torkjetil** [comment]
Og er koblet til alle arkivenhet objekter 
![image](https://user-images.githubusercontent.com/366886/99388334-b4b77880-28d5-11eb-9460-732594cc9eed.png)

**Comment by jarleborsheim** [comment]
Utgår. Det er en saksfunksjon
