### ISSUE TITLE
Synkrone tjenester

### ISSUE THREAD

**Issue by sturtzel** [ks-no/gi-arkiv-2.0#22]
I en del tilfeller trenger fagsystemet svar fra server før den kan fortsette, f.eks. hvis sak finnes brukes denne, hvis ikke lages ny.

Et bibliotek med synkrone tjenester kan gjøre terskelen lavere for systemer som ikke trenger asynkron overføring / har anledning til å vente (lenge) på svar (i en tråd).

Vi bør uansett ha noen eksempler på dette. De første eksemplene er alle fire and forget.

**Comment by HarryMyrene** [comment]
Visma: Det avgjørende her vil være hvor lang tid det kan gå før svar kommer. I Visma når arkivmeldingen sendes, så skjer dette i bakgrunnen og saksbehandler vil ikke merke om det tar litt tid for å sjekke om mappen finnes eller om ny må lages. Kvittering om arkivert (eller ikke) vil måtte oppdatere hendelsen som trigget arkivering.

**Comment by sturtzel** [comment]
Synkrone tjenester er tenkt som tillegg og håndtert av et bibliotek. Hvis det skal sjekkes om sak finnes og hvis nei, lag sak, deretter lag journalpost, er det mye enklere for et fagsystem med synkrone tjenester.

**Comment by jarleborsheim** [comment]
Vi tar ikke dette nå
