### ISSUE TITLE
Håndtere transaksjoner, og støtte for flere 'arkivjobber' i samme arkivmelding

### ISSUE THREAD

**Issue by overunedriveklepp** [ks-no/gi-arkiv-2.0#23]
Er det gjort tanker rundt hvordan håndtere flere "arkiv-operasjoner" i samme arkivmelding? Er tanken å kunne både opprette mappe og journalpost i samme arkivmelding, og evt. lage flere mapper med flere journalposter i samme arkivmelding?
I så fall; hvordan håndteres feil-situasjoner der noe gikk gjennom ok, og noe feiler?

Visma foreslår å begrense slik støtte til et minimum for å begrense konsekvenser og cornercases som kan oppstå. For eksempel maks støtte en ny mappe med en ny journalpost, eller aller helst kun støtte å opprette en tom mappe, og så må en ny arkivmelding sendes for å opprette journalpost i en mappe. For arkivering av en journalpost er et naturlig å støtte x antall tilhørende dokumenter siden de er en del av journalposten og feiler noe her så blir enten journalposten arkivert med alle dokumenter, eller så blir ingenting arkivert.

**Comment by jarleborsheim** [comment]
Vi har bestemt at det skal bli en arkivering pr melding.
Stenger denne saken
