### ISSUE TITLE
Brukstilfelle 14: Restanseliste fra fagsystem

### ISSUE THREAD

**Issue by sturtzel** [ks-no/gi-arkiv-2.0#24]
GI Arkiv bør kun ha tjenester for arkivering. Brukstilfelle 14 er derfor utenfor scope da det er et brukstilfelle for GI Sak.

Også ekspedering bør være en tjeneste i GI Sak.
Utfordringen her er oppdatering av metadata i arkivet som tar vare på info om at forsendelsen ikke bare er sendt, men også åpnet (når transporttjenesten gir dette som respons (etter hvert)).

**Comment by HarryMyrene** [comment]
Visma: For sky-tjenestene ekspederer vi direkte fra fagsystemet til KS SvarUt. Dette for å få hente inn responser fra forsendelsen som svarut gir. Når ok ekspedert, arkiveres forsendelsen. 

Restanseliste vil nok Visma sende utenom GI-Arkiv, slik at det her vil bli en forskjell om kunde benytter visma sin arkivkjerne eller fra annen leverandør som ikke da vil håndtere restanser.

**Comment by sturtzel** [comment]
Arkivmessig er det spørsmål om attributter for forsendelsesmåte og forsendelsesstatus. Begge finnes i Noark 4, men ingen av dem i Noark 5.

Siden status blir oppdatert etter forsendelsen er gjort, til dels lenge etter, vil evt. støtte for denne være en tjeneste for å oppdatere statusen.

Selve forsendelsen bør gjøres av fagsystemet som også er det som kan følge opp evt. feil i forsendelsen.

**Comment by jarleborsheim** [comment]
Utgår
