### ISSUE TITLE
Søk vs Hent

### ISSUE THREAD

**Issue by JanIvarMoldekleiv** [ks-no/gi-arkiv-2.0#25]
I søk vil vi normalt returnere et redusert datasett nok for opplisting. Ved Hent har vi behov for å hente hele elementet

Retur er uansett arkivmelding: 
1) Vi må definere hva det reduserte datasettet skal bestå i som minimum. Mer data enn dette er valgfritt for leverandør
2) Vi må definere hva som skal trigge uthenting av komplett element.
Jeg foreslår at  henting av komplett element trigges ved angivelse av systemid.

Prosess blir da:
Søk - få liste over elementer
  velg element - 
  gjør nytt søk men denne gang med systemid som parameter.

**Comment by sturtzel** [comment]
Hent bør kunne gjøres som i GI 1.1 med entydig nøkkel som kan være systemID, eksternnøkkel eller f.eks. et saksnummer.

Hent bør kunne ha parameter som for 1.1 m.h.t. hvor mye data (hvilke underobjekter) som skal hentes.

**Comment by HarryMyrene** [comment]
Visma: 
Fra et fagsystem vil det primært bli "Hent" for å sjekke om mappe på nivå 1 og mappe på nivå 2 eksisterer fra før eller ikke.

**Comment by sturtzel** [comment]
Det ble definert egen xsd for søkeresultat for noen uker siden. Da forsvant muligheten for å få hele resultatet tilbake.

Gjeldende forslag er å ta med include-parametere i søkekallet, samt angivelse av kun id-er, minimumsdata eller alt+angitte underobjekter.
