### ISSUE TITLE
Standard kodelister?

### ISSUE THREAD

**Issue by sturtzel** [ks-no/gi-arkiv-2.0#26]
Ref. ArkivLett-prosjektet. Standard kodelister?
Statuskoder?
Klassifikasjonssystem? (Kan være flere på en mappe, så standard for arkivdel holder ikke).
PartRolle?
Tilgangsrestriksjon?
Korrespondanseparttype?
Dokumenttype?
Variantformat?
Format?
Andre?

Hvis det skal være faste verdier: Mulighet for egendefinerte verdier i tillegg? Hvis ikke, hvordan håndtere avvikende verdier som ligger i arkivet? Hvis faste: Enumeration eller tekst?

Og/eller tjenester for å hente kodelister som i GI 1.1?

Klassifikasjonssystemene har f.eks. ofte forskjellig benevning mellom installasjoner selv når de beskriver samme (som eiendomsarkiv, K-koder med fellesklasser og fagklasser, desimale arkivkoder, klientarkiv, personalarkiv).

**Comment by HarryMyrene** [comment]
Visma:

Statuskoder?
- M053-Journalstatus blir vel nå "Arkivert"
- M054-Dokumentstatus blir vel nå "Dokumentet er ferdigstilt"
Klassifikasjonssystem? 
- Ikke en del av tjenestegrensesnittet i dag, settes i arkivet. Må få sjekket med utvikling, men vi henter vel i dag klassifikasjonssystem som ligger på arkivdelen - uavhengig av hva det heter??
Partrolle?
- Trodde ikke vi skulle ha med part i denne versjonen av grensesnittet. Er jo omarbeidd i forhold til tidligere "sakspart". Men partrolle tenker jeg fagsystemet må få bruke sine egen benevnelser på.. 
Tilgangsrestriksjon?
- Tenker verdien bør være "Unntatt offentlighet" (obligatorisk verdi) eller "Blank". 
Dokumenttype?
- Ingen obligatoriske verdier. Tenker fagsystemet må få putte inn sine egne kategoriseringer av dokumenttype. 
Variantformat?
- Et fagsystem vil vel benytte "Arkivformat" i og med at produksjonsformatet ligger i fagsystemet. Kan bli en utfordring dersom vi skal arkivere der "deler av dokumentet er skjermet".

Ser det som en utfordring om fagsystemet skal hente kodelister, og spesielt hvis disse skal være egendefinerte ute hos en kunde. Årsaken er at det må settes opp en mapping-algoritme mellom verdier som de enkelte fagsystemen benytter, og koder som en kunde har satt opp, Mener derfor at raskeste vei til mål å akseptere obligatoriske verdier i N5v5 som standard, og evt. benytte andre etter nærmere avtale mellom arkiv-leverandør og fagsystem.

**Comment by sturtzel** [comment]
Det er ikke gitt at M053 kun vil være Arkivert, det kan være en annen ferdigkode hvis arkivet f.eks. skal stå for produksjon av arkivformat.

M054 vil nok kun ha denne, ja.

Klassifikasjonssystem kan være flere ved at det benyttes sekundære koder. Men bruken vil nok heller konfigureres.

Part bør være med. Denne er svært mye brukt i bl.a. byggesak. Part på journalpost er neppe videre utbredt (ennå). Partrolle vil nok ha en del standardverdier (fra ArkivLett).

Eksisterende arkivkjerner har gjerne flere koder for unntatt offentlighet, f.eks. egen for personalsaker med strengere skjerming internt enn koder for unntatt offentlighet eksternt.

Hvis det skal være fritt frem for dokumenttyper, må dette defineres. Disse brukes bl.a. for gjenfinning av spesielle typer dokumenter, ref. Arkivlett.

Det er behov for flere variantformat. Her kommer bl.a. produksjonsformat, sladdet format (hvis offentlig journal skal hente data fra arkivkjernen), signert format.

Tjeneste for kodelister kan være aktuell for fagsystemer som vil presentere eksisterende verdier i et brukergrensesnitt, samt hvis det ikke blir kodeobjekt i arkivmeldingen (slik det er både i GI 1.1 og i N5WS). Ref. også ArkivLett (og GI 1.1) m.h.t. kodeverdier.

**Comment by jarleborsheim** [comment]
Løst
