### ISSUE TITLE
Sokeresultat og klassifikasjon

### ISSUE THREAD

**Issue by sturtzel** [ks-no/gi-arkiv-2.0#36]
Noark 5s hierarkiske datamodell egner seg ikke fullt ut for søkeresultat.

Når man søker etter mapper / saksmapper trenger man å vite hele settet med klassifikasjon. I dag har man arkivdel (referanseArkivdel) og sekundær klassifikasjon (referanseSekundaerKlassifikasjon). Det beste er å døpe om sekundær klassifikasjon til kun klassifikasjon slik at det er tydelig at alle klasser skal kunne returneres her. Alternativet er å legge til et felt for primær klassifikasjon. Også primær klassifikasjon må ha minOccurs 0.

Klassifikasjonen bør dessuten flyttes fra saksmappe til mappe om man ikke tar det for gitt at det alltid er saksmappe.

**Comment by jarleborsheim** [comment]
Løst
