### ISSUE TITLE
Identifisering av filer i arkivmeldingen

### ISSUE THREAD

**Issue by ArveCorneliussen** [ks-no/gi-arkiv-2.0#38]
Er det slik at dokumentbeskrivelse i arkivmeldingen kun identifiserer filer med filnavn?
Hva med et ansettelsessystem som arkiverer en ansettelsessak med 10 journalposter for søknadene der hver journalpost har et hoveddokument med navn "søknad.pdf".
Det vil vel ikke fungere?

**Comment by jarleborsheim** [comment]
Vi legger til filnavn som ny property av typen string. Dette er da filnavnet slik det vises for bruker. 
referanseDokumentfil er filnavn i asic-e zip-pakken.

**Comment by jarleborsheim** [comment]
Denne er vel løst og kan stenges? Men vi bør kanskje dokumentere det tydeligere at det er slik det er?

**Comment by jarleborsheim** [comment]
Løst
