### ISSUE TITLE
samordne datamodell med move-messagetypes

### ISSUE THREAD

**Issue by JanIvarMoldekleiv** [ks-no/gi-arkiv-2.0#4]
Datamodell som er brukt i dette prosjektet bør være kompatibel med datamodell som utarbeides i difi sitt prosjekt for move - move-messagetypes:
https://github.com/difi/move-messagetypes

**Comment by torkjetil** [comment]
https://difi.github.io/felleslosninger/eformidling_nm_message.html#arkivmelding

Prosess | Dokumenttype
-- | --
urn:no:difi:profile:arkivmelding:planByggOgGeodata:ver1.0 |  
  | urn:no:difi:arkivmelding:xsd::arkivmelding
urn:no:difi:profile:arkivmelding:helseSosialOgOmsorg:ver1.0 |  
  | urn:no:difi:arkivmelding:xsd::arkivmelding
urn:no:difi:profile:arkivmelding:oppvekstOgUtdanning:ver1.0 |  

Prosess definert her kan kansje utvides for avsender i FIKS for til å dekke behov for å si noe om hvilken arkivdel meldingen skal tilhøre i mottakende system.
planByggOgGeodata kan få et nivå til(kansje fra Los begreper https://psi.norge.no/los/struktur.html) med byggesaksbehandling, arealplanlegging, oppmåling, ...

**Comment by JanIvarMoldekleiv** [comment]
Move messagetypes er oppdatert med endringer fra Ragnar Sturtzel. Det er små endringer. Må avklares med DIFI @ekorra når disse endringene skal inn i next move.

**Comment by torkjetil** [comment]
Bruker modellen her https://github.com/ks-no/move-messagetypes/blob/master/arkivmelding/arkivmelding.xsd
