### ISSUE TITLE
Mangler søkefelt i FIKS Arkiv på sak.part.kontaktperson

### ISSUE THREAD

**Issue by ArveCorneliussen** [ks-no/gi-arkiv-2.0#40]
Du kan lagre feltet i arkivmeldingen og det er støtte for det i Geointegrasjon 1.1
(Vet ikke om det er noen som bruker det i Geointegrasjon nå, da...)

Det mangler også søkefelt fra GI på sak.part.referansenummer (orgnummer/personnummer)
Det er nok veldig aktuelt, å finne alle saker der et firma er sakspart f.eks.

**Comment by sturtzel** [comment]
Spesielt søk via ID-nummer er viktig.

**Comment by jarleborsheim** [comment]
@ArveCorneliussen og @sturtzel. Ta gjerne en titt på PR ☝️

**Comment by sturtzel** [comment]
Organisasjonsnummer og fødselsnummer er det som er viktig.

Da blir det sak.part.organisasjonsid og sak.part.personid.

Men har noe falt ut her for person? Angivelse av om det er fødselsnummer, D-nummer, ...

**Comment by jarleborsheim** [comment]
Da har jeg endret til sak.part.organisasjonsid og sak.part.personid her https://github.com/ks-no/fiks-arkiv-client-dotnet/pull/23

Angivelse om det er fødselsnummer, D-nummer osv har vi snakket om i denne PR'en også? https://github.com/ks-no/fiks-arkiv-client-dotnet/pull/18

Jeg oppretter et eget issue på dette i stedet.

**Comment by jarleborsheim** [comment]
@ArveCorneliussen og @sturtzel: ta gjerne en nyt titt på PR om det er godkjent: https://github.com/ks-no/fiks-arkiv-client-dotnet/pull/23

**Comment by sturtzel** [comment]
Ref. kommentar på PR.

Kanskje slå sammen organisasjonsid og personid til ett felt og så legge til et typefelt som kan omfatte både orgnr, fnr, dnr, ...?

**Comment by jarleborsheim** [comment]
Vi må sjekke utenlandske personnummer før vi bestemmer oss.

**Comment by jarleborsheim** [comment]
Kan vi avslutte dette issuet siden vi landet dette med personid og organisasjonsid?

**Comment by sturtzel** [comment]
Ja, vi har tatt en gjennomgang til nå på søk.

Det kommer sikkert opp nye behov under pilottestingen, men bedre at vi avventer konkrete behov enn av vi legger til masse "nice to have" nå.
