### ISSUE TITLE
Referanser fra registrering til mappe den tilhører

### ISSUE THREAD

**Issue by sturtzel** [ks-no/gi-arkiv-2.0#41]
Hvis registreringer/journalpost ikke arkiveres samtidig med mappe/saksmappe, er det behov for en referanse til denne så arkiveringen blir i riktig mappe. Referansene bør inneholde samme muligheter som i dagens GeoIntegrasjonstjenester. I dag må man hente ut systemID for denne for å kunne angi koblingen.

Det foreslås at modellen for registrering utvides med følgende felt, minOccurs=0, maxOccurs=1:
referanseForelderMappeEksternNøkkel

Det foreslås at modellene for journalpost og arkivnotat utvides med følgende felt, minOccurs=0, maxOccurs=1:
saksnummer (sammensatt med saksaar og sakssekvensnummer)

Siden disse feltene skal kunne både sendes inn og hentes ut, foreslås det at restriksjonen med choice i registrering fjernes. Det må heller lages en regel for hva som skal gjelde om det sendes inn flere nøkler i et ny-kall.

**Comment by sturtzel** [comment]
Ser at denne allerede lå som issue 37. Men her er det konkret forslag, så lar 37 utgå.

**Comment by jarleborsheim** [comment]
Løst
