### ISSUE TITLE
Fagsystemets tilganger til data i arkivet

### ISSUE THREAD

**Issue by sturtzel** [ks-no/gi-arkiv-2.0#42]
I GeoIntegrasjon er det pålogging, noe som gir tilganger basert på brukers rettigheter.

Via Fiks vet vi i realiteten ingenting om bruker, kun om fagsystem. Kan man jukse vedrørende fagsystem? Hvis ikke kan man legge tilgangskontrollen på fagsystemnivå. Evt. ekstra skjerming er da opp til fagsystemet. Ref. dokument fra Arve distribuert etter Fiks Politiker-møtet 23/9.

**Comment by idar** [comment]
Vi oppgir hvilket system som hører til kontoen som sender til arkivet. En kan gi tilgang basert på system som snakker med arkivet.
