### ISSUE TITLE
Søk på sak posisjon

### ISSUE THREAD

**Issue by ArveCorneliussen** [ks-no/gi-arkiv-2.0#43]
Dette er tre ulike søkeparametere nå sakpunktx, sakpunkty og sakpunktz.
Men det gir ingen mening å søke bare på sakpunktx eller bare sakpunkty
Jeg forslår derfor at dette endres til en søkeparameter "sakpunkt" med tre verdier: x, y og z

**Comment by sturtzel** [comment]
I GI har man BBOX, gi meg alle saker innenfor dette området. Det er vel reelt det man trenger siden man aldri vil få tilslag på en sak gitt eksakt punkt (avrundingsfeil).

**Comment by jarleborsheim** [comment]
Stenger denne da PR er godkjent og merget
