### ISSUE TITLE
Savner søk på mappetype

### ISSUE THREAD

**Issue by ArveCorneliussen** [ks-no/gi-arkiv-2.0#44]

**Comment by sturtzel** [comment]
Søk gitt mappetype eller liste over typer? For det siste bør vi nok ha tjenester slik de var i GI så det er mulig å gjøre beslutninger i fagsystemet ut fra data i arkivet.

**Comment by jarleborsheim** [comment]
@ArveCorneliussen Har du en oppdatering her?

**Comment by jarleborsheim** [comment]
Den er med nå. Lukker saken
