### ISSUE TITLE
Duplikate meldinger om arkivering

### ISSUE THREAD

**Issue by idar** [ks-no/gi-arkiv-2.0#45]
Et tenkt scenario: arkiveringsmelding blir sendt og avsender ikke får kvittering innen forventet tid fordi arkivet bruker lenger tid på arkivering enn tenkt. Fagsystem sender da arkivmeldingen på nytt.

Hva gjør vi da for å unngå dobbelarkivering.

Bruker eksternnøkkel og gir feilmelding eksisterer allerede?
Legger på en ekstra id som identifiserer at dette er samme meldingen som kommer igjen.

**Comment by sturtzel** [comment]
Hodet i meldingen bør inneholde en referanse fra avsender som skal være med i alle kvitteringsmeldinger, ikke kun referansen Fiks IO setter på. Dette gjør det mulig å sende samme melding på nytt og det gjør det mulig for mottager å detektere at det er en duplikatmelding hvis det bare har tatt for lang tid slik at avsender trodde meldingen ikke var gått gjennom.

Får mottager en duplikatmelding, foreslår jeg at mottager sender OK tilbake med meldingsinnhold som om det var originalmeldingen som ble håndtert.

**Comment by JanIvarMoldekleiv** [comment]
Jeg tenker at dette ikke bør skje. Dersom vi har mottatt meldingen på arkivets side så er meldingen mottatt og vårt problem. Dersom meldingen fortsatt ligger i fiks.io kan vi diskutere om fiks.io bør ha deteksjon for duplikater. 
F.eks. noe som dette: 
https://github.com/noxdafox/rabbitmq-message-deduplication

1) Meldinger som er mottatt av arkivet sender mottatt-kvittering. 
2) Er ikke mottattkvittering sendt er meldingen enten ikke mottatt eller noe har gått galt. 
3) Etter et langt tidsrom (flere dager) kan man vurdere å sende  en arkiveringsmelding på nytt. 
Det er da fint om Fiks IO støtter deduplisering som over. 
4) Arkivet mottar og arkiverer alt det vi får.

**Comment by sturtzel** [comment]
Utfordringen er hvis avsender sender samme melding på nytt og det ikke finnes noe i meldingen (fra avsender) som gjør det mulig å detektere at dette er et duplikat.

**Comment by jarleborsheim** [comment]
Vi har lagt på klientMeldingID i Fiks-IO. Denne skal klienten bruke for å indikere at en melding blir sendt på nytt. Altså bruke samme id igjen i klientMeldingID.

**Comment by jarleborsheim** [comment]
Vi anser denne som løst
