### ISSUE TITLE
Tjeneste for å hente dokumentinnhold

### ISSUE THREAD

**Issue by sturtzel** [ks-no/gi-arkiv-2.0#47]
Søketjenestene som er definert så langt returnerer mapper/saksmapper og registreringer/journalposter.

Registrering har objektet dokumentbeskrivelse som igjen inneholder objektet dokumentobjekt. Dette objektet har attributtet referanseDokumentfil.

Da det ikke er ønskelig med åpninger rett inn i arkivet, bør denne referansen være noe som kan brukes i en ny tjeneste via Fiks Arkiv HentDokument.

Tjenesten bør håndtere dokumentene slik tjenesten for lagre journalpost med dokumenter gjør det.

**Comment by jarleborsheim** [comment]
Ref møte 04-11-2021 trenger vi også å kunne hente en mappe og journalpost og må lage schemas for alle 3.
Vi kan gjøre alle disse i samme slengen.
- mappe (flags for å antyde hva man vil ha med. Som i søk)
- journalpost (flags for å antyde hva man vil ha med. Som i søk)
- dokumentfil (kun id som input for å hente filen)

**Comment by jarleborsheim** [comment]
Jeg antar vi kan stenge denne?

**Comment by sturtzel** [comment]
Antagelig.

Endelig svar får vi når vi er i gang (evt. problemer med tilganger++). Men da får vi heller ta det opp igjen.

**Comment by jarleborsheim** [comment]
Flott. Da stenger jeg denne.
