### ISSUE TITLE
XSD-ene for søkeresultat er alle like

### ISSUE THREAD

**Issue by sturtzel** [ks-no/gi-arkiv-2.0#48]
Hvis man søker og vil ha nøkler tilbake, skal vel ikke XSD-en inneholde mapper?
Hvis man søker og vil ha minimum skal det vel heller ikke være fulle objekter?

Det er tre XSD-er for søkeresultat. Disse må tilpasses det som skal returneres.

**Comment by jarleborsheim** [comment]
Dette tror jeg skal være løst nå. Stemmer det @sturtzel?

**Comment by sturtzel** [comment]
Ja, denne løste vel dette: https://github.com/ks-no/fiks-arkiv-client-dotnet/commit/b1e8301f07c3910e166a83fb9d51af3a36c8e6d1

**Comment by jarleborsheim** [comment]
Flott! Da stenger jeg den
