### ISSUE TITLE
Mulighet for å få med mappe i søkeresultat etter registrering?

### ISSUE THREAD

**Issue by sturtzel** [ks-no/gi-arkiv-2.0#49]
Dette er mest aktuelt for journalpost med saksmappe.

**Comment by jarleborsheim** [comment]
Dette burde vært en del av søkeresultat utvidet og minimum som et nytt resultat. Gjerne med navnet journalpostMedSaksmappe.  At man får med ekstra felt fra f.eks. saksmappe når man får resultat for en journalpost. 
Det vil si at vi hadde tatt med feltene fra saksmappe-minimum inn i et nytt type journalpost objekt.

**Comment by jarleborsheim** [comment]
Løst i PR. Stenger saken
