### ISSUE TITLE
Skal vi kutte virksomhetsspesifikke metadata fra søkeargumentene i versjon 1?

### ISSUE THREAD

**Issue by sturtzel** [ks-no/gi-arkiv-2.0#50]
Uten krav til bruk av VSM er det kun mulig med tekstsøk i blobdata. Vi bør derfor utsette denne fra "where-delen".

**Comment by jarleborsheim** [comment]
Tar du en titt på PR når du har tid @sturtzel ? :)

**Comment by sturtzel** [comment]
@jarleborsheim 
Den ser OK ut.

**Comment by jarleborsheim** [comment]
Stenger issue etter godkjent PR
