### ISSUE TITLE
Sortering av søkeresultat

### ISSUE THREAD

**Issue by sturtzel** [ks-no/gi-arkiv-2.0#52]
Det er ikke mulig å angi sortering av søkeresultat.

Legge på dette? Men da må det begrenses til felt i hovedobjektet.

**Comment by jarleborsheim** [comment]
Denne skal være løst nå. Stemmer ikke det @sturtzel? 
Her: https://github.com/ks-no/fiks-arkiv-client-dotnet/blob/main/KS.Fiks.IO.Arkiv.Client/Schema/sok.xsd#L18

**Comment by sturtzel** [comment]
Ja, men vi må ta en runde på noen av feltene, f.eks.:
Saksbehandler: Initialer, navn, ???
Status: Kode, beskrivelse, ???
Det kan hende at listen må reduseres.

**Comment by jarleborsheim** [comment]
Den er grei 👍

**Comment by idar** [comment]
Etter møtet:
<xs:enumeration value="mappe.opprettetDato"/> Default
<xs:enumeration value="sak.saksdato"/>
 
  
  {
  	<xs:enumeration value="sak.saksaar"/>
	<xs:enumeration value="sak.saksekvensnummer"/>
  }
 
 <xs:enumeration value="registrering.opprettetDato"/> Default
 <xs:enumeration value="journalpost.journaldato"/>
{
   <xs:enumeration value="journalpost.journalaar"/>
   <xs:enumeration value="journalpost.journalsekvensnummer"/>
}
<xs:enumeration value="journalpost.journalpostnummer"/>

**Comment by jarleborsheim** [comment]
Løst
