### ISSUE TITLE
Oppdatering av data

### ISSUE THREAD

**Issue by sturtzel** [ks-no/gi-arkiv-2.0#53]
Jeg foreslår at det lages egne kall for oppdatering.
Dagens kall beholdes for nye saker/journalposter.
Det kan være behov for eget kall for å legge til nye dokumenter, men det vil stride litt mot forutsetningen om at det er ferdige journalposter (ekspederte/journalførte) som arkiveres.

Oppdateringskallet kan ha to parametere:
Arkivmeldingen som for ny-kallene.
En liste over data som skal fjernes.

Tomme felt i arkivmeldingen for oppdatering ignoreres (original verdi beholdes). Dette muliggjør forenklede grensesnitt som ikke trenger å hente ut hele objekter før data oppdateres.

Listen for fjerning kan ha to felt:
Navn på feltet som skal fjernes
Evt. en SystemID

Feltnavnet i listen kan være samme som for søk.
Hvis navnet er et objektnavn, f.eks. mappe.part er det hele forekomsten som skal slettes.
Er det angitt noe i ID-feltet er det en part (eller merknad, ...) som skal slettes.
Er det ikke angitt noe i ID-feltet er det alle som skal slettes / erstattes.

Dette skulle være både fleksibelt og kraftig nok.

**Comment by harhus** [comment]
Kallset Eirik Viken (Guest)
Brukerhistorie fra Digibarnen Fagsystem:

- Det kommer et innkommende brev, f.eks. en bekymringsmelding om et barn. Denne meldingen knyttes til en aktiv sak på barnet saksbehandler tror det gjelder. Det sendes en arkivmelding med registreringen av journalposten på barnets saksmappe. Etter noen dager oppdages det at bekymringsmelding gjaldt et annet barn enn det først ble knyttet til, (f.eks. et søsken). I fagsystemet så rettes dette opp ved at bekymringsmeldingen legges på riktig barn. Leder autoriserer flyttingen av dokumentet via en godkjenningsprosess i fagsystemet.

- Fagsystemet sender en ny arkivmelding med registeringen av bekymringsmeldingen på riktig barn.

- Det er ønskelig at fagsystemet kan sende en melding til arkivet om at den tidligere sendte arkivmeldingen er en feilføring.

**Comment by sturtzel** [comment]
Vi må gå opp et prinsipp her: Spissede endringsmeldinger for journalpost eller generelle oppdateringer som sender inn hele journalpostobjektet. For sak er det sistnevnte som ligger an til å bli løsningen (ellers blir det fort mange meldinger). For journalpost kan det være fornuftig å ha spesialmeldinger, men da trengs som minimum Fordel journalpost, Endre skjerming på journalpost, Avskriv journalpost, Flytt journalpost, Legg til merknad på journalpost, evt. også Arkiver (avslutt) journalpost. Og sikkert flere...

**Comment by harhus** [comment]
Forslag fra Arve: 
Det er basert på de samme prinsipper som protokollen mellom GUI’et og forretningslogikk’en i Public 360° (selv om selve XML syntaksen er helt annerledes). 
Det har fungert i Public 360° i 20 år 😊

1.	Alle items må ha en ekstern nøkkel, hvis ikke er det ikke mulig å operere på de individuelt (slette/oppdatere)
2.	Alle items (mappe, part, registrering, korrespondansepart etc) har et obligatorisk attributt: operasjon = opprett/oppdater/slett
a.	Hvis du har «opprett» på ett nivå, må alle underliggende items også ha «opprett» (det kunne jo vært implisitt, men kanskje attributtet eksplisitt må nevnes?)
b.	Hvis du skal opprette noe nytt under et item, må item’et nevnes med «oppdater», mens det som opprettes har operasjon = «opprett» (f.eks. en ny registrering i en mappe)
3.	Alle items må ha en ekstern nøkkel for å gjøre det mulig å operere på de individuelt (slette/oppdatere)
4.	Ved oppdatering blir alle felter som er nevnt oppdatert. Felter som ikke skal oppdateres nevnes ikke.
Det gjør det ikke mulig å «tømme» individuelle felter for verdi (en kan bare slette underliggende «items», merknader saksparter etc), 
men jeg kan ikke komme på noen eksempler der det er et behov. Skal en nullstille et tekstfelt, kan en jo nevne det i oppdateringen med tom verdi.
5.	Jeg foreslår at toppnoden i arkivmeldingen enten er mappe eller registrering.
a.	Hvis du skal tillate «opprett» på registrering som toppnode, må du ha attributter som identifiserer mappen i registreringen.
Jeg synes kanskje det å opprette en registrering i en mappe burde starte med «oppdater» på mappe med «opprett» på registreringen.
Jeg synes kanskje registrering som toppnode bare gir mening for «oppdater» og «slett»
b.	Skal du opprette/oppdatere/slette et underliggende element f.eks. en sakspart, må du alltid nevne noden over med operasjon=«oppdater» på denne.
Vi kunne f.eks. hatt «part» som toppnode og tillatt oppdater/slett direkte på denne noden, men da blir syntaksen for å legge til en sakspart veldig forskjellig fra å oppdatere/slette en sakspart, synes kanskje ikke det er lurt.
6.	Vi må diskutere hva som skal være mulig å endre på et journalført dokument. 
Eller så kan vi overlate det til de enkelte arkivene. 
Hvis du forsøker å oppdatere noe på et endelig arkivert dokument, vil de fleste arkiver ikke tillate dette, hvis du ikke er arkivar.
En leverandør kunne jo tenke seg å opprette en konto for arkivarer i Fiks IO og at alt som kommer på den kontoen betraktes som noe «en arkivar gjør», da vil det typisk være tillatt å endre veldig mye mer enn dersom en vanlig saksbehandler oppdaterer.

Vanskelig å forklare og forstå dette i prosa, men eksemplene under gir mer mening.
Hvis vi skal forenkle denne syntaksen for klientene, foreslår jeg at det gjøres ved å lage metoder i klientbiblioteket i stedet for å tillatte veldig mange variasjoner i arkivmeldingen.

/Arve

<minimum-eksempler>
       
       <arkivmelding>
              <mappe type="saksmappe" operasjon="opprett">
                     <referanseEksternNoekkel>
                            <fagsystem>Fagsystem X</fagsystem>
                            <noekkel>1234</noekkel>
                     </referanseEksternNoekkel>
                     <tittel>Test</tittel>
              </mappe>
       </arkivmelding>

       
       <arkivmelding>
              <mappe type="saksmappe" operasjon="oppdater">
                     <referanseEksternNoekkel>
                            <fagsystem>Fagsystem X</fagsystem>
                            <noekkel>1234</noekkel>
                     </referanseEksternNoekkel>
                     <tittel>Test oppdatert</tittel>
              </mappe>
       </arkivmelding>

       
       <arkivmelding>
              <mappe type="saksmappe" operasjon="opprett">
                     <referanseEksternNoekkel>
                            <fagsystem>Fagsystem X</fagsystem>
                            <noekkel>1234</noekkel>
                     </referanseEksternNoekkel>
                     <tittel>Test</tittel>
                     <part operasjon ="opprett">
                            <referanseEksternNoekkel>
                                   <fagsystem>Fagsystem X</fagsystem>
                                   <noekkel>1234</noekkel>
                            </referanseEksternNoekkel>
                            <partNavn>Arve</partNavn>
                     </part>
                     <registrering type="journalpost" operasjon ="opprett">
                            <referanseEksternNoekkel>
                                   <fagsystem>Fagsystem X</fagsystem>
                                   <noekkel>1234</noekkel>
                            </referanseEksternNoekkel>
                            <tittel>Bestilling av oppmålingsforretning ...</tittel>
                            <journalposttype>I</journalposttype>
                            <dokumentetsDato>2021-03-20</dokumentetsDato>
                            <korrespondansepart operasjon="opprett">
                                   <referanseEksternNoekkel>
                                           <fagsystem>Fagsystem X</fagsystem>
                                           <noekkel>1234</noekkel>
                                   </referanseEksternNoekkel>
                                   <korrespondanseparttype>EA</korrespondanseparttype>
                                   <korrespondansepartNavn>Arve</korrespondansepartNavn>
                            </korrespondansepart>
                            <dokumentbeskrivelse operasjon ="opprett">
                                   <referanseEksternNoekkel>
                                           <fagsystem>Fagsystem X</fagsystem>
                                           <noekkel>1234</noekkel>
                                   </referanseEksternNoekkel>
                                   <dokumenttype>SØKNAD</dokumenttype>
                                   <dokumentstatus>F</dokumentstatus>
                                   <tittel>Rekvisisjon av oppmålingsforretning</tittel>
                                   <tilknyttetRegistreringSom>H</tilknyttetRegistreringSom>
                                   <dokumentobjekt operasjon ="opprett">
                                          <referanseEksternNoekkel>
                                                  <fagsystem>Fagsystem X</fagsystem>
                                                  <noekkel>1234</noekkel>
                                          </referanseEksternNoekkel>
                                          <versjonsnummer>1</versjonsnummer>
                                          <variantformat>P</variantformat>
                                           <format>PDF</format>
                                          <filnavn>Rekvisisjon.pdf</filnavn>
                                        <referanseDokumentfil>rekvisisjon.pdf</referanseDokumentfil>
                                   </dokumentobjekt>
                            </dokumentbeskrivelse>
                     </registrering>
              </mappe>
       </arkivmelding>

       
       <arkivmelding>
              <mappe type="saksmappe" operasjon="oppdater">
                     <referanseEksternNoekkel>
                            <fagsystem>Fagsystem X</fagsystem>
                            <noekkel>1234</noekkel>
                     </referanseEksternNoekkel>
                     <part operasjon ="opprett">
                            <referanseEksternNoekkel>
                                   <fagsystem>Fagsystem X</fagsystem>
                                   <noekkel>1234</noekkel>
                            </referanseEksternNoekkel>
                            <partNavn>Arve</partNavn>
                     </part>
              </mappe>
       </arkivmelding>

       
       <arkivmelding>
              <mappe type="saksmappe" operasjon="oppdater">
                     <referanseEksternNoekkel>
                            <fagsystem>Fagsystem X</fagsystem>
                            <noekkel>1234</noekkel>
                     </referanseEksternNoekkel>
                     <part operasjon ="slett">
                            <referanseEksternNoekkel>
                                   <fagsystem>Fagsystem X</fagsystem>
                                   <noekkel>1234</noekkel>
                            </referanseEksternNoekkel>
                     </part>
              </mappe>
       </arkivmelding>

       
       <arkivmelding>
              <mappe type="saksmappe" operasjon="oppdater">
                     <referanseEksternNoekkel>
                            <fagsystem>Fagsystem X</fagsystem>
                            <noekkel>1234</noekkel>
                     </referanseEksternNoekkel>
                     <part operasjon ="oppdater">
                            <referanseEksternNoekkel>
                                   <fagsystem>Fagsystem X</fagsystem>
                                   <noekkel>1234</noekkel>
                            </referanseEksternNoekkel>
                            <partRolle>Ansvarshaver</partRolle>
                     </part>
              </mappe>
       </arkivmelding>

</minimum-eksempler>

**Comment by Arve-Corneliussen** [comment]
Eksempler diskutert i møte:
<eksempel>
	<arkivmelding>
		<mappe>
			<operasjon>oppdater</operasjon>
			<systemid>12345</systemid>   
			<tittel>Ny tittel</tittel>       
			<part>
				<operasjon>oppdater</operasjon>
				<systemid>7890</systemid>           
				<navn>Dette blir oppdatert</navn>       
				<resten-av-feltene-må-nevnes />
			</part>       
			<part>
				<operasjon>ny</operasjon>
				<navn>Nytt part navn</navn>       
			</part>       
			<part>
				<operasjon>slett</operasjon>
				<systemid>9876</systemid>       
			</part>   
		</mappe>
	</arkivmelding>

	<arkivmelding>
		<mappe type="saksmappe" operasjon="oppdater">
			<tittel/>
			<id>123</id>
			<partsoppdatering operasjon ="slett">
				<id>123</id>
			</partsoppdatering>
		</mappe>
	</arkivmelding>

	<arkivmelding-oppdater>
		<oppdater-mappe type="saksmappe">
			<tittel>Ny tittel</tittel>       
			<id>123</id>
			<oppdater-part>
				<id>123</id>
			</oppdater-part>
			<ny-part>
				<id>123</id>
			</ny-part>
		</oppdater-mappe>
	</arkivmelding-oppdater>

</eksempel>

**Comment by jarleborsheim** [comment]
Vi stenger denne saken da vi har laget oppdaterings meldinger
