### ISSUE TITLE
Jeg ønsker meg en Ping melding på alle protokoller slik at vi kan teste at en konfigurasjon faktisk fungerer

### ISSUE THREAD

**Issue by Arve-Corneliussen** [ks-no/gi-arkiv-2.0#55]

**Comment by jarleborsheim** [comment]
Forstår jeg deg riktig at det slik at dere opplever av og til å ha noen feil i konfigurasjon som ikke feiler før dere forsøker å sende en melding @Arve-Corneliussen? Hvilke feil er det dere typisk ser da? 
Når ser dere for dere å sende en slik Ping melding? Er det ved oppstart, eller jevnlig for å sjekke at man kan kommunisere?

**Comment by Arve-Corneliussen** [comment]
Det er ingen spesielle feil det er snakk om her, det er alltid en god ide å kunne se status på en integrasjon og kunne se at den faktisk er oppe og går. Jeg ser for meg at vi periodisk sender ping meldinger til alle servere vi har i vår konfigurasjon og viser status på alle servere i admin modulen vår for Fiks IO. Men dette er ikke noe vi kommer til å prioritere på kort sikt.

**Comment by jarleborsheim** [comment]
Ok. Jeg tar det opp internt 👍

**Comment by jarleborsheim** [comment]
Vi kom fram til at dette kan løses ved at vi lager en ny meldingstype (ping-melding) som dere kan sende til dere selv? 
Da ser dere selv at den kommer fram som den skal. Den nye meldingstypen har ingen payload og er der kun for at vi skal kunne gjenkjenne at det var en "ping".

**Comment by Arve-Corneliussen** [comment]
Ja, en Ping Request melding uten payload som alle servere og klienter må støtte. Meldingen svares med en Ping Response melding, også uten payload

**Comment by jarleborsheim** [comment]
Men trenger man en Ping Response hvis mottaker er deg selv? Da vet jo du at den har kommet fram?

**Comment by Arve-Corneliussen** [comment]
Nei, jeg vet vel at FIKS IO har mottatt den, men jeg vet vel ikke om den er mottatt og håndtert av serveren på den andre siden

**Comment by jarleborsheim** [comment]
Vi venter litt med denne og ser på forskjellige muligheter.
Den hører ikke hjemme i FIKS Arkiv som en del av den standarden, men må være en generell funksjonalitet.
Ikke høyt prioritert.

**Comment by jarleborsheim** [comment]
Er dette noe som best løses ved at vi tilbyr "health" endepunkt for Fiks-Protokoll? Da vil man se at sin egen konto er oppe og healthy. Den kan eventuelt også vise meldinger man har sendt som evt da ikke er hentet av mottaker. Det gir samme effekt som ping melding, men man slipper å håndtere ping melding og svare på de for å sjekke helse i "koblingene"?
