### ISSUE TITLE
Samle inn forskjellige typer oppstart av sak

### ISSUE THREAD

**Issue by AndersOstmoe** [ks-no/gi-arkiv-2.0#6]
Samle inn brukstilfeller.

Norkart, Norconsult, Geomatikk, Geodata, Visma, Powel... Se klientsystemer.

Vi bør også finne systemer som ikke er brukere i dag. Bruke referansegruppa.

**Comment by idar** [comment]
Brukstilfeller for system:
Husbanken: Arkivere journalpost med filer. Kan være fint å kunne se liste over jornalposter og filer på sak.
