### ISSUE TITLE
Angivelse av om det er fødselsnummer, D-nummer osv mangler

### ISSUE THREAD

**Issue by jarleborsheim** [ks-no/gi-arkiv-2.0#61]
Som diskutert i issue #40  

Se diskusjon i denne PR'en også: https://github.com/ks-no/fiks-arkiv-client-dotnet/pull/18

**Comment by jarleborsheim** [comment]
Vi må sjekke utenlandske personnummer før vi bestemmer oss.

**Comment by jarleborsheim** [comment]
Kan vi stenge denne da?

**Comment by sturtzel** [comment]
Tror den er grei nå. Vi får heller åpne igjen hvis det viser seg at noe må endres når vi kommer i pilot.
