### ISSUE TITLE
Mappe i Mappe

### ISSUE THREAD

**Issue by JanIvarMoldekleiv** [ks-no/gi-arkiv-2.0#62]
Vi trenger en avklaring på om vi skal godta hele mappestrukturer i en melding, eller om vi skal legge til grunn at dersom det kommer mappe i mappe så finnes foreldermappe fra før.

Vi foreslår følgende regler i første omgang:
- Mapper kan referere til eksisterende mappe - den må da ha vært opprettet tidligere
- En foreldermappe kan ikke inneholde registreringer

**Comment by sturtzel** [comment]
Siden vi har sagt at saksmappe og journalpost kan komme i samme melding, bør vi vel støtte også mappe i mappe i samme melding.

Men jeg er skeptisk til for mye. Hva skal skje hvis det går OK med de fem første hovedobjektene, men det feiler på det sjette? Det gjelder også når både saksmappe og journalpost(er) overføres samtidig. Jeg tror vi gjør lurt i å begrense i versjon 1.

**Comment by jarleborsheim** [comment]
Vi dokumenterer dette som regler for arkivering og endrer mappereferanser fra * til 1.

**Comment by jarleborsheim** [comment]
Har også forsøkt å dokumentere det [her](https://ks-no.github.io/fiks-plattform/tjenester/fiksio/arkiv/#begrensninger-og-regler-for-arkivering)

Tekst:

> Begrensninger og regler for arkivering
> Arkivmelding støtter ikke å registrere flere mapper i et hierarki, altså mapper i mapper, i en enkelt arkivmelding. Registrering av ny undermappe må da registreres hver for seg. Mapper kan altså bare referere til eksisterende mappe, som må da ha vært opprettet tidligere.
> En foreldermappe kan ikke inneholde registreringer. Altså en mappe som inneholder andre mapper skal bare inneholde mapper.

**Comment by jarleborsheim** [comment]
Kan vi stenge denne da?
