### ISSUE TITLE
Generere XSD/ JSON fra modeller. Avgjøre hva som egner seg.

### ISSUE THREAD

**Issue by AndersOstmoe** [ks-no/gi-arkiv-2.0#7]

**Comment by torkjetil** [comment]
xsd støtter arv som er brukt en del i noark, json schema må løse opp arv til aktuelle realiseringer. Metode/konvensjon må utarbeides for json schema

**Comment by torkjetil** [comment]
Lagt inn json eksempel her - https://github.com/ks-no/gi-arkiv-2.0/blob/master/eksempel/json/utgaaendejournalpost.json

Xsd bør vi vel bruke move typene - https://github.com/difi/move-messagetypes/blob/master/arkivmelding/Lagre_i_eksisterende_mappe.xml
