### ISSUE TITLE
Savner mappetype i datastrukturen for mappe

### ISSUE THREAD

**Issue by Arve-Corneliussen** [ks-no/gi-arkiv-2.0#71]
Ref mappetype i GI Arkiv Oppdatering

**Comment by sturtzel** [comment]
Ja, denne må inn! Sentralt felt, holder ikke med varianter a la Saksmappe.

**Comment by jarleborsheim** [comment]
- Nytt felt på mappe som er valgfritt. Hvis ikke det settes noe så er det tomt.
- Ikke kunne endres
- Kode - av typen kode
- Skal kunne filtreres på søk

**Comment by jarleborsheim** [comment]
Løst og stenger saken
