### ISSUE TITLE
Avgradering: Savner avgraderingskode på skjerming

### ISSUE THREAD

**Issue by Arve-Corneliussen** [ks-no/gi-arkiv-2.0#72]
I GI Arkiv er det et felt skjermingOpphoererAksjon på skjerming som angir hva som skal skje når avgraderingsdatoen nås. (Automatisk avgradering, vurdere avgradering etc) I arkivmeldingen er det avgraderingsdato, men det mangler felt for avgraderingskode. Det er imidlertid felt for skjermingMetadata, skjermingsdokument og skjermingsvarighet. Kan vi diskutere dette på neste standardiseringsmøte?

**Comment by sturtzel** [comment]
Mener jeg har kommentert det med skjerming tidligere. Jeg heller mot å beholde mest mulig av "Noark 4" her, d.v.s. ikke bruke tekstlig oppramsing slik det er i Noark 5. Dette er hvordan vi gjorde det i GI også.

**Comment by Arve-Corneliussen** [comment]
I Public 360 er det arbeidslister for saker/dokumenter som skal vurderes for avgradering og automatikk i avgradering av saker/dokumenter som har nådd sperrefristen, til det trenger vi en avgraderingskode

**Comment by sturtzel** [comment]
Dette har vel alle arkivkjerner. Om vi ikke tar med koden må den ha en standardverdi i oppsettet basert på f.eks. tilgangskoden. Tilsvarende bør det vel være en standardverdi for avgraderingsdato slik at ikke alle klientsystemer trenger å ta stilling til den gitt at de følger normal periode gitt av lovparagrafene.

**Comment by Arve-Corneliussen** [comment]
Endring av objektet for skjerming:
- skjermingMetadata, skjermingsdokument fjernes
- skjermingsvarighet fjernes
- skjermingopphoererdato beholdes
- nytt felt for skjermingOpphoererAksjon: Sjekk GI for koder (A, G; S, AU)

**Comment by jarleborsheim** [comment]
Trenger tips til hvor jeg finner beskrivelse for kodene nevnt i oppgaven. Har ikke klart å finne de på  GI eller Noark dokumentasjon. Lager kodeliste når jeg finner beskrivelsene og navn.

**Comment by sturtzel** [comment]
Denne?

![image](https://user-images.githubusercontent.com/27213616/168085145-0ef80568-796c-4353-b1bd-4437f1a2469e.png)

**Comment by jarleborsheim** [comment]
> Denne?
> 
> ![image](https://user-images.githubusercontent.com/27213616/168085145-0ef80568-796c-4353-b1bd-4437f1a2469e.png)

Søkte på feil ord. Fant dokumentet men ikke koden ;)

**Comment by sturtzel** [comment]
Ja, den

**Comment by jarleborsheim** [comment]
Løst og stenger saken
