### ISSUE TITLE
Punkter og planIdenter i arkivmeldingen

### ISSUE THREAD

**Issue by Arve-Corneliussen** [ks-no/gi-arkiv-2.0#73]
Kan en plansak være knyttet til flere planident'er?
I 360 Plan&Build kan en plansak bare gjelde en plan, det kan aldri være flere.

Arkivmeldingen har også en liste med punkter på en sak.
I byggesaker er det ett punkt i 360 Plan & Build (punktet angir hvor tiltaket skal utføres).
I plansaker kan det være null, en eller flere områder der hvert område kan modelleres som et sett med punkter, men du kan ikke modellere to eller flere områder som en liste med punkter.

Disse tingene må vi diskutere i neste standardiseringsmøte.

**Comment by sturtzel** [comment]
En plan i en sak.
Område må kunne angis, men kan en plan omfatte områder som ikke henger sammen?

**Comment by Arve-Corneliussen** [comment]
Ja, en plan kan ha flere områder som ikke er overlappende

**Comment by Arve-Corneliussen** [comment]
Endringer i saksmappe:

1. Kun en planidentifikasjon på saksmappe
2. Kun ett punkt på saksmappe

**Comment by jarleborsheim** [comment]
Løst og stenger saken
