### ISSUE TITLE
Manglende adresse på eiendommer og manglende gnr/bnr på bygninger

### ISSUE THREAD

**Issue by Arve-Corneliussen** [ks-no/gi-arkiv-2.0#74]
Hvis arkivet skal bli søkbart på eiendommer og bygninger, mener jeg saksmappe 

1. Eiendommer ikke bare kan inneholde matrikkelnummer (gnr/bnr/snr/fnr), men også adresse (gateadresse, postkode og postadresse og kommunenummer)
2. Bygninger ikke bare kan inneholde bygningsnummer, men også matrikkelnummer og adresse

**Comment by Arve-Corneliussen** [comment]
Endringer på saksmappe:

1. Legge på adresse-liste på saksmappe: Adresse, postnummer og poststed

**Comment by jarleborsheim** [comment]
Løst og stenger saken
