### ISSUE TITLE
Ny meldingstype for å laste opp nytt dokumentobjekt på eksisternede dokumentbeskrivelse

### ISSUE THREAD

**Issue by jarleborsheim** [ks-no/gi-arkiv-2.0#75]
Man skal kunne sende nytt dokumentobjekt med f.eks. skjerming til en eksisterende dokumentbeskrivelse.

**Comment by sturtzel** [comment]
Behovet er typisk for å laste opp sladdet versjon av et skjermet dokument. Dette gjøres i ettertid, ofte etter at det har kommet en innsynsforespørsel.

Den vil også kunne brukes av en konverteringstjeneste for å laste opp arkivformat, men dette vil nok normalt håndteres av arkivkjernen via interne tjenester.

**Comment by jarleborsheim** [comment]
Løst. Stenger.
