### ISSUE TITLE
Hvordan skal saksår/sekvensnummer håndteres i opprett sak?

### ISSUE THREAD

**Issue by Arve-Corneliussen** [ks-no/gi-arkiv-2.0#76]
I Public 360 er dette verdier som blir automatisk opprettet av systemet når en ny sak opprettes
Skal vi overstyre denne automatikken og legge in fagsystemets saksår/sekvensnummer i arkivet?
Da kan vi risikere å få duplikate saksnummer i arkivet.
På den annen side vil arkivet få et annet saksnummer enn fagsystemet på noe som er samme sak?
Det er kanskje best at arkivet tildeler saksår/sekvensnummer når en ny sak opprettes i arkivet og at disse dataene kommer tilbake til fagsystemet og fagsystemet setter saksår/sekvensnummer på saken i fagsystemet. I så fall kan ikke saksår/sekvensnummer være med i arkivmeldingen.

Dette trenger vi å diskutere i standardiseringsforumet.

**Comment by sturtzel** [comment]
Saksnummeret i arkivet skal antagelig inngå i offentlig journal. Jeg foreslår at arkivsaksnummeret reserveres arkivet og at fagsystemer benytter andre begreper. Vi opererer med to forskjellige serier i dagens integrasjoner for eByggesak. Feltene bør være i arkivmeldingen slik at de kan hentes ut.

**Comment by Arve-Corneliussen** [comment]
Returmeldingen fra søk bruker saksmappe objektet, feltene kan derfor ikke fjernes fra saksmappe, men kan ignoreres fra saksmappe ved arkivering av ny sak
