### ISSUE TITLE
Opprette ny registrering i eksisterende mappe

### ISSUE THREAD

**Issue by Arve-Corneliussen** [ks-no/gi-arkiv-2.0#77]
Jarle sier at feltet referanseForelderMappe skal brukes til å angi hvilken mappe registreringen/journalposten skal legges inn i.
Men referanseForelderMappe er bare en string. En må vel kunne angi saksår/sekvensnr eller ekstern id også?

Dette må vi diskutere i standardiseringsforumet

**Comment by sturtzel** [comment]
På vei inn må man kunne bruke tilsvarende mekanismer som for GI inkl. ekstern nøkkel. På vei ut er vel SystemID viktigst, samt saksår/sakssekvensnummer om mappen over er en saksmappe. Ved mappe i mappe er den generelt ikke det...

**Comment by Arve-Corneliussen** [comment]
Konklusjon: referanseForelderMappe erstattes med choice mellom disse tre:
- Saksnr (saksaar, sekvensnr)
- Extern nøkkel fra fagsystemet
- SystemId

**Comment by sturtzel** [comment]
OK med innsjekken, men dette bør ses i sammenheng med metadatakatalogens referanseTilMappe, samt referanseTilRegistrering, referanseTilMoeteregistrering, referanseTilKlasse og referanseTilDokumentbeskrivelse.

Ideelt burde alle referansene (i hvert fall som inndata) være lik det som ble valgt som referanseForelderMappe her. For registreringer kan det f.eks. også være kombinasjonen saksnummer/sakssekvensnummer/journalpostnummer, samt journalaar/journalsekvensnummer.

**Comment by jarleborsheim** [comment]
Jeg ser nå at i vår eksempelkode så returnerer vi et objekt av typen ReferanseForelderMappe som er SystemID i f.eks JournalpostHentKvittering (altså når man henter en journalpost). Burde dette vært et objekt som har SystemID, ReferanseEksternNoekkel, og/eller Saksnr? 
Endrer vi det i arkivstruktur.xsd så blir det likt for alle meldiner som returnerer data på hent eller kvittering.
https://github.com/ks-no/fiks-arkiv-specification/blob/931b4e956a29f3bafa29edfb15b5cc747d6314eb/Schema/V1/arkivstruktur.xsd#L169

**Comment by Arve-Corneliussen** [comment]
Det er bare saksmapper som har saksaar/sekvensnummer, ikke mapper

**Comment by jarleborsheim** [comment]
Ok. Men hvis man henter en journalpost. Kan da forelder være en saksmappe og det ville være naturlig å få saksnummer?

**Comment by sturtzel** [comment]
Litt usikker på hva du mener. JournalpostHent skal vel returnere journalpost. Tenker du inne i denne (referanseForelderMappe i objektet Registrering)?

Siden visning i de fleste tilfeller da vil være saksaar/sakssekvensnummer-journalpostnummer som identifikator bør vi ha en måte å få med oss de på. Kanskje vi trenger en inkluderSaksmappe likevel som tar med seg de viktigste feltene fra saken (referanse, tittel)?

**Comment by jarleborsheim** [comment]
Ja. Det jeg ser er at nå man f.eks. returnerer en journalpost i en hent journalpost respons, altså [journalpostHentResultat.xsd](https://github.com/ks-no/fiks-arkiv-specification/blob/main/Schema/V1/journalpostHentResultat.xsd) så returnerer man en journalpost fra arkivstruktur.xsd. Den har da en ReferanseForeldermappe fra registrering som da er kun en SystemID. Jeg lurte bare på om det ville være naturlig at den var lik ReferanseForeldermappe slik vi endret den til å være i [arkivmelding.xsd ](https://github.com/ks-no/fiks-arkiv-specification/blob/931b4e956a29f3bafa29edfb15b5cc747d6314eb/Schema/V1/arkivmelding.xsd#L134)

**Comment by sturtzel** [comment]
Jeg heller mot det. Så kan det komme nye typer mappe med andre referanser, men neppe i overskuelig fremtid.

**Comment by jarleborsheim** [comment]
Denne er løst
