### ISSUE TITLE
Tittel kontra offentlig tittel

### ISSUE THREAD

**Issue by Arve-Corneliussen** [ks-no/gi-arkiv-2.0#78]
For diskusjon i standardiseringsgruppa: Ved opprettelse av sak er tittel det eneste obligatoriske feltet i et arkivsystem, alle andre felter kan tildeles standardverdier. Jeg stusser litt på at arkivmeldingen inneholder Tittel og OffentligTittel, der Tittel da antakelig er ment som avskjermet tittel, dvs unntaket. Burde det ikke ikke være Tittel og AvskjermetTittel i arkivmeldingen, der AvskjermetTittel er unntaket og som regel tom, mens Tittel alltid må ha verdi?

**Comment by sturtzel** [comment]
Feltet heter offentligTittel (M025 i Noark 5).

Det kan godt angis 0..1 på feltet. Arkivkjernen vil da sette offentligTittel = tittel.
