### ISSUE TITLE
Referanse til sak i MappeOppdatering SaksmappeOppdatering

### ISSUE THREAD

**Issue by Arve-Corneliussen** [ks-no/gi-arkiv-2.0#82]
Her er det bare SystemId og ReferanseEksternNoekkel som identifiserer saken som  skal oppdateres.
Det burde vel vært konsistent med andre saksreferanser og hatt en referanseTilMappe med 

- Saksnr (saksaar, sekvensnr)
- Extern nøkkel fra fagsystemet
- SystemId

I neste standardiseringsmøte bør vi vel også gå igjennom feltene i MappeOppdatering og SaksmappeOppdatering
Det mangler felter som admin-enhet, sakstatus, eiendommer, bygninger, planident, punkt, avskjerming, merknader, nøkkelord etc

**Comment by sturtzel** [comment]
I GI benyttes SaksNoekkel som er en av følgende:
Saksnummer
EksternNoekkel
SystemId
Så de må vi ha.

Når det gjelder felt å endre trenger gi GI+. GI har status, ekstern nøkkel, ansvarlig (både saksbehandler og enhet), matrikkelnummer, byggid, punkt, sakspart (kalles nå kun part i Noark 5), planident, merknad og tilleggsinfo (virksomhetsspesifikke metadata). Finnes de kun på saksmappe, blir det slik også for oppdatering. Skjerming må med og også tittel, kryssreferanse og klassering. Det kommer sikkert flere behov når vi kommer lenger i implementeringen av klienten vår.

PS: For journalpost er det i dag behandlingsansvarlig (både enhet og saksbehandler), avskrivning (!), merknad, korrespondanseparter og tilleggsinfo (VSM). Også her må skjermingen, kryssreferansene og tittelen kunne oppdateres. Også her kommer det sikkert til flere.

**Comment by jarleborsheim** [comment]
Laget en pull request hvor vi har lagt til referanseTilMappe som nevnt i issue her. Skal jeg også legge til de feltene som ble nevnt eller skal dette tas opp i plenum?

**Comment by sturtzel** [comment]
For vår del gjør det ikke noe om det utsettes en uke. Men det nærmer seg.

**Comment by jarleborsheim** [comment]
Vi lar forslaget stå i pull request og stenger denne når den er merget

**Comment by jarleborsheim** [comment]
Merget og vi stenger saken
