### ISSUE TITLE
Kryssreferanse inneholde mer enn bare SystemID?

### ISSUE THREAD

**Issue by jarleborsheim** [ks-no/gi-arkiv-2.0#84]
Skal vi endre kryssreferanse til å ha mer enn bare SystemID der det gir mening? For saksmappe kan det være f.eks. både SystemID, EksternNoekken og Saksnummer. 

Det må da kanskje være en choice på vei "inn" og alle feltene med "ut" igjen fra arkiv?

**Comment by sturtzel** [comment]
Ideelt burde det være alle muligheter (for journalpost både saks- og journalpostnummer, samt journalnummer) både inn og ut, men inn er viktigst. Og kryssreferansene må også kunne oppdateres (ref. issue 82).

**Comment by jarleborsheim** [comment]
Da har jeg laget en [pull-request ](https://github.com/ks-no/fiks-arkiv-specification/pull/40) hvor jeg har lagt på en systemID på kryssreferanse på vei ut fra arkiv og endret referanseTilMappe og referanseTilRegistrering å ha flere identifikatorer. Men burde det være en choice mellom identifikatorene i referanseTilMappe og referanseTilRegistrering? Nå kan man sende inn 0 eller flere?

Foreslår også at vi endrer hentRegistrering og hentMappe til å bruke de nye referanseTilMappe og referanseTilRegistrering fra metadatakatalog etter vi har merget inn denne endringen.

**Comment by sturtzel** [comment]
Siden Noark 5 tillater at et element kan referere mer enn et objekt i samme referanse tror jeg vi skal la denne delen være som den er. Men jeg tviler på om det er intensjonen til Noark at det skal være slik... Evt. bruk vil vel være at det registreres en kryssreferanse til en registrering som ligger i en mappe og at man da velger å registrere også referansen til mappen for å kunne adressere denne direkte.

Ja, konsistent bruk av referanser tilsier at hentRegistrering og hentMappe bruker samme referanseobjekt som i kryssreferanse.

**Comment by jarleborsheim** [comment]
Denne er løst
