### ISSUE TITLE
Undersøke identifikaor

### ISSUE THREAD

**Issue by AndersOstmoe** [ks-no/gi-arkiv-2.0#9]

**Comment by ekorra** [comment]
Eidas bruker 2 bokstavs landidentifikater beskrevet i ISO 3166-1 alpha-2
https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

Brukes i Edias i for av at man sier land man kommer fra/land man vil logge inn/personidetifikator
feks: nordmann som bruker svnesk tjeneste NO/SE/PID
