### ISSUE TITLE
Ikke lenger mulig å verifisere alle typer søk hvor resultat er nøkler i validator

### ISSUE THREAD

**Issue by jarleborsheim** [ks-no/gi-arkiv-2.0#90]
Siden søkeresultat for nøkler er nå kraftig redusert så kan ikke validatoren vite lenger om man egentlig har truffet innenfor et datosøk f.eks.. 
Dette er ikke sikkert er et stort problem men det betyr at vi ikke kan ha noen veldig gode tester på alle typer søk i validatoren uten at man evt gjør nye kall for å hente detaljer om hvert resultat for å verifisere detaljene. Det er ikke mulig i validatoren.

Dette gjelder f.eks. søk på saksmapper mellom to datoer hvor man ber om søkeresultat -> nøkler. Da får man ikke i resultatet tilbake noe som egentlig kan verifisere at det stemmer. Da må man hente hver og en i resultatet for å se på detaljene. 
En sånn type test må skrives som en integrasjonstest i så fall.

**Comment by sturtzel** [comment]
En mulighet er å kjøre de tre typene søk i sekvens og sjekke om det som kommer når man velger minimum og nøkler samsvarer med det som man får ved fullt resultat.

**Comment by jarleborsheim** [comment]
Ja, det er også en mulighet for feil med en liten sjanse for at noe har endret seg mellom søkene. Men det å kjøre 3 søk med 3 resultat og så sammenlikne er dessverre også noe som ikke validatoren støtter nå.

Jeg skal undersøke litt mer hva som kan være løsningen.

**Comment by sturtzel** [comment]
Skal det være validering av søk må det være via tjenester som putter inn data og så henter ut igjen. Søk er litt komplisert slik. Så jeg tror ikke risikoen for forskjellig resultat er så stor / at den er akseptabel.

**Comment by jarleborsheim** [comment]
Vi har som mål at vi løser dette i stedet med integrasjonstester, som etter hvert kan også kjøres fra validatoren
Stenger issue
