### ISSUE TITLE
Ta bort arkivstruktur referansen i arkivmeldingOppdatering.xsd

### ISSUE THREAD

**Issue by jarleborsheim** [ks-no/gi-arkiv-2.0#93]
Vi må ta bort referansen til arkivstruktur.xsd i arkivmeldingOppdatering.xsd som betyr at vi kopierer inn de typene som ble referert til inn i arkivmeldingOppdatering.xsd.
Skal vi også ta bort referansen til arkivmelding.xsd og kopiere de typene inn også?

**Comment by sturtzel** [comment]
Litt usikker på spørsmålet. Vi kan ha referanser til våre egne typer uten å duplisere dem. Men det er risikabelt å basere seg på URLer og innhold utenfor det vi har kontroll på.

**Comment by jarleborsheim** [comment]
Vi lar den stå

**Comment by jarleborsheim** [comment]
Fikset. Kom ut med versjon 0.0.15 av nuget pakken `KS.Fiks.Arkiv.Models.V1`
