### ISSUE TITLE
Savner payload filnavn på ugyldigforespørsel og serverfeil

### ISSUE THREAD

**Issue by Arve-Corneliussen** [ks-no/gi-arkiv-2.0#94]
FiksArkivPayloadHelper.GetPayloadFilnavn har ikke mapping for disse meldingstypene

**Comment by jarleborsheim** [comment]
Foreslår `feilmelding.xml` som filnavn på payload for feilmeldingene. 
Her er PR: https://github.com/ks-no/fiks-arkiv-models-dotnet/pull/18

**Comment by sturtzel** [comment]
Har ikke sjekket koden, så det kan hende det ligger svar på spørsmålene min der.

Er dette innholdet i 500-feil etc.?
Vil det naturlig være en XML? Modell for XML-filen?

**Comment by jarleborsheim** [comment]
Innholdet er vel ut i fra kontekst vil jeg tro. `Ugyldigforespørsel` bør vel helst gi en pekepinn på hva som var ugyldig (ugyldig xml f.eks. i henhold til skjema eller ugyldig id?) mens `Serverfeil` kan nok som du skriver egentlig være en 500-feil og da spørs det vel hva man ønsker å gi av tilbakemelding til avsender? 

Grunnen til at vi gikk for XML var fordi resten av protokollen er XML og vi fant ut at hver feilmelding bør være innenfor en protokoll og ikke en felles feilmelding for alle protokoller. For Politisk Behandling vil disse feilmeldingene være i json-format f.eks. siden resten av den protokollen er json. 

Modellene er med i nuget-pakken. 
Se gjerne eksempel her fra Fiks-Arkiv og arkivsystem mock som vi har laget der: https://github.com/ks-no/fiks-arkiv/blob/master/dotnet-source/ks.fiks.io.arkivsystem.sample/Generators/FeilmeldingGenerator.cs

**Comment by sturtzel** [comment]
Er OK, slo opp i koden for https://github.com/ks-no/fiks-arkiv-specification/blob/main/Schema/V1/feilmeldingBase.xsd og så denne i spesifikasjonen: <xs:element name="feilmelding" type="xs:string" />

D.v.s. at selve feilmeldingen ikke trenger noen XML-koding og kan inneholde en full stacktrace om nødvendig. Evt. burde det vært to felt, en for feilmelding og en for stacktrace ("mer info") der den siste kunne vært minOccurs 0.

Har som sagt ikke studert denne koden, men <xs:element name="feilId" type="n5mdk:ID" />: Noe som bare kan genereres eller noe som må tas vare på for senere oppslag i server? Hvis den ikke må kunne brukes for senere oppslag kunne den antagelig vært minOccurs 0. Men jeg ser nytten.

**Comment by jarleborsheim** [comment]
Vi kan godt ta en diskusjon om feilmeldingene skal justeres med disse tingene på neste møte. 
Men jeg merger inn den endringen jeg har gjort nå siden det er en fiks for manglende filnavn. Så kan disse andre tinene være en egen endring hvis det skal gjøres.

**Comment by jarleborsheim** [comment]
Fikset og stenger saken
