### ISSUE TITLE
HentMappe, HentJournalpost og HentDokumentfil finnes, men hva med HentSaksmappe, HentRegistrering og HentDokument

### ISSUE THREAD

**Issue by Arve-Corneliussen** [ks-no/gi-arkiv-2.0#95]
1. Det bør vel være slik at HentMappe kan returnere saksmappe eller mappe. Da bør også request meldingen kunne inneholde Saksaar/sekvensnummer.
2. Tilsvarende bør HentJournalpost hete HentRegistrering som kan returnere Journalpost eller Registrering og tilsvarende med nøkler i request meldingen
3. HentDokumentfil bør vel hete HentDokument og returnere metadata om dokumentet i tillegg til selve fila. Her bør du vel kunne angi variantformat i kriteriet (arkivformat, offentlig format etc) med offentlig format som default, arkivformat hvis offentlig format ikke finnes

**Comment by sturtzel** [comment]
1: Nye spesialiseringer kan inneholde andre nøkler, f.eks. møtemappe med utvalg og tidspunkt for møtet, evt. en egen møte-id, byggesak med matrikkelnummer, plansak med planid. P.t. vil vel alle disse tas via VSM, men det burde vært noe minimumsdata som var felles. Jeg tror vi bør holde oss til de generiske, spesielt siden utgangspunktet for hent normalt vil være et søk eller egen eksternnøkkel.
2: Møtesakregistrering, møtedokumentregistrering, arkivnotat, ... Det kan bli noen nøkkelsett. Men tjenestenavnet bør hete HentRegistrering, ja.
3: Her var vel tanken at journalposten skulle ha med metadata for dokumentbeskrivelse (og dokumentobjekt) slik at man kunne bestemme seg for hvilken dokumentversjon man vil hente med HentDokumentfil. Så denne tror jeg vil skal beholde som den er. I et brukergrensesnitt kan man da klikke på et dokumentikon og få opp selve dokumentet.

Hvis en mappe eller en registrering er en spesialisering er det denne som må returneres. Ellers ville vi ha måttet lage svært mange tjenester.

**Comment by sturtzel** [comment]
Sett nærmere på denne vs. det som er gjort m.h.t. referanser i arkivmeldingen.

Ja, døp om Journalpost.Hent til Registrering.Hent tilsvarende det generiske for mappe. Resultatet bør være spesialiseringen der denne finnes. Hvis ikke må det legges på en parameter som styrer dette.

Parametrene i complexType journalpostHent og mappeHent bør gjøres om tilsvarende det som er gjort i issue 87 med bruk av referanseJournalpost. Ulempen er at denne er eksplisitt for journalpost og den tilsvarende for mappe eksplisitt for saksmappe. Et alternativ er å bruke innmaten fra referanseJournalpost, d.v.s. at i stedet for tre felt der det ene ikke har mening uten saksnummer, bør man ha journalnummer og saksJournalpostnummer, og for hent mappe saksnummer.

**Comment by jarleborsheim** [comment]
Se forslag til endringer i pull request her: https://github.com/ks-no/fiks-arkiv-specification/pull/37
Og her: https://github.com/ks-no/fiks-arkiv-models-dotnet/pull/19

**Comment by jarleborsheim** [comment]
@sturtzel Var de to pull requestene over ok? Det er supert hvis du inne på pull request gjør en review og godkjenner så jeg med 100% sikkerhet vet at den er godkjent :) Ønsker å merge dette inn før jeg gjør endringen mtp avsluttetDato og avsluttetAv er feilaktig satt som required.

**Comment by jarleborsheim** [comment]
Tar en nøyere titt men vi mener denne er ferdig

**Comment by jarleborsheim** [comment]
Ser ut til å være løst. Stenger saken
