### ISSUE TITLE
Inkluder i sok.xsd bør fjernes eller endres

### ISSUE THREAD

**Issue by sturtzel** [ks-no/gi-arkiv-2.0#99]
For det første er den spesifisert som 0-1. Har man valgt å få med klasser kan man ikke få med parter. For det andre bestemmer respons hva man får tilbake. Klasser er uaktuelle til registrering (journalpost).

Alternativt må det være en liste med valg basert på hvilket objekt man har søkt etter og dermed hvilke objekter som kan inkluderes sammen med hovedobjektene i søkeresultatet.

Ref. også tilsvarende for Hent-meldingene der inkluder er splittet.

**Comment by jarleborsheim** [comment]
En løsning kan være at vi endrer `respons` til å være et valg mellom forskjellige responstyper som så har kun de inkluder typene som gir mening. Da kunne vi også flyttet inn sorteringsfelt dit slik at de også bare var mulig å velge gyldige verdier for hver responstype?

Her er en PR som er et midlertidig forslag og for å kunne diskutere løsning: https://github.com/ks-no/fiks-arkiv-specification/pull/36

**Comment by jarleborsheim** [comment]
PR godkjent og merget. Stenger denne saken
